// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjRtKsvbg4Rv62z8-BR1ZBQSwE4mcAvWw',
    appId: '1:614377257092:web:990637d2d60cc2d89faad1',
    messagingSenderId: '614377257092',
    projectId: 'dailygrocer-97d43',
    authDomain: 'dailygrocer-97d43.firebaseapp.com',
    storageBucket: 'dailygrocer-97d43.appspot.com',
    measurementId: 'G-L3PQ47PJ68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy8wbe_WgkP5xUveydOwKpEMTUp3b9F4E',
    appId: '1:614377257092:android:743d4eca2b7518989faad1',
    messagingSenderId: '614377257092',
    projectId: 'dailygrocer-97d43',
    storageBucket: 'dailygrocer-97d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOM-_a4Br-m7eHm5i4ATUYXwLcayLGrak',
    appId: '1:614377257092:ios:17ab168ff00619259faad1',
    messagingSenderId: '614377257092',
    projectId: 'dailygrocer-97d43',
    storageBucket: 'dailygrocer-97d43.appspot.com',
    iosBundleId: 'com.example.dailyGrocer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOM-_a4Br-m7eHm5i4ATUYXwLcayLGrak',
    appId: '1:614377257092:ios:17ab168ff00619259faad1',
    messagingSenderId: '614377257092',
    projectId: 'dailygrocer-97d43',
    storageBucket: 'dailygrocer-97d43.appspot.com',
    iosBundleId: 'com.example.dailyGrocer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjRtKsvbg4Rv62z8-BR1ZBQSwE4mcAvWw',
    appId: '1:614377257092:web:301deffd54128a049faad1',
    messagingSenderId: '614377257092',
    projectId: 'dailygrocer-97d43',
    authDomain: 'dailygrocer-97d43.firebaseapp.com',
    storageBucket: 'dailygrocer-97d43.appspot.com',
    measurementId: 'G-DFLKVCGNPJ',
  );
}
